# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 541bbc2be404ff655ea7d4438ea38db9e09f41f93cb3a70486f52a8375b5002358ac692c8013a1a7aa8c4dfa2d643abbc817778e91ed00969c11ce3a45ad1ae1

test:
  secret_key_base: 7306c3c3e7170d3f691a7a4330cf351910b5742bdb27240814f8f8fe04511ca8f2bc52fea39c6651c8d41577c41bef95974876cc43ad15737d413e55fd101428

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
